config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :goals, only: [:index]
  end
  resource :session
  resources :goals, except: [:index]
end

app/models/goal.rb
# == Schema Information
#
# Table name: goals
#
#  id         :integer          not null, primary key
#  content    :string(255)      not null
#  ppublic    :boolean          not null
#  completion :boolean          not null
#  user_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

class Goal < ActiveRecord::Base
  validates :content, :user_id, presence: true
  validates :ppublic, :completion, inclusion: [true, false]
  belongs_to :user
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  user_name       :string(255)      not null
#  password_digest :string(255)      not null
#  session_token   :string(255)      not null
#  created_at      :datetime
#  updated_at      :datetime
#

class User < ActiveRecord::Base
  
  attr_reader :password
  after_initialize :ensure_session_token
  validates :user_name, :password_digest, presence: true
  validates :password, length: {minimum: 6, allow_nil: true}
  has_many :goals
  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end
  
  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
  
  def self.find_by_credentials(username, password)
    user = User.find_by(user_name: username)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end
  
  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end
  
  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
  helper_method :logged_in?, :current_user
  def current_user
    @current_user = User.find_by(session_token: session[:session_token])
  end
  
  def log_in(user)
    session[:session_token] = user.reset_session_token!
  end
  
  def log_out
    current_user.try(:reset_session_token!)
    session[:session_token] = nil
  end
  
  def logged_in?
    !!current_user
  end
  
  def require_user
    redirect_to new_session_url unless logged_in?
  end

end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :require_user
  before_action :require_right_user, only: [:edit]
  def new
    @goal = Goal.new
    render :new
  end
  
  def create
    @goal = Goal.new(goal_params)
    @goal.user_id = current_user.id
    if @goal.save
      redirect_to user_url(current_user)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end
  end
  
  def show
    @goal = Goal.find(params[:id])
    render :show
  end
  
  def edit
    @goal = Goal.find(params[:id])
    render :edit
  end
  
  def update
    @goal = Goal.find(params[:id])
    if @goal.update(goal_params)
      redirect_to goal_url(@goal)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :edit
    end
  end
  
  def destroy
    goal = Goal.find(params[:id])
    goal.destroy
    redirect_to user_url(current_user)
  end
  
  private
  
  def goal_params
    params.require(:goal).permit(:content, :ppublic, :completion)
  end
  
  def require_right_user
    @goal = Goal.find(params[:id])
    unless @goal.user == current_user
      redirect_to user_url(current_user)
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    @user = User.new
    render :new
  end
  
  def create  
    @user = User.find_by_credentials(params[:user][:user_name], 
                                     params[:user][:password])
    if @user
      log_in(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = ["Invalid username or password"]
      @user = User.new :user_name => params[:user][:user_name]
      render :new
    end
  end
  
  def destroy
    log_out
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user, except: [:new, :create]
  def index
    @users = User.all
  end
  
  def new
   @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end
  
  def show
    @user = User.find(params[:id])
    # fail
    render :show
  end
  
  private
  def user_params
    params.require(:user).permit(:user_name, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/edit.html.erb
<h1>Edit the Goal</h1>
<form action="<%= goal_url(@goal) %>" method="post" accept-charset="utf-8">
  <input  type="hidden" name="_method" value="PUT">
  <label for="goal_content" ><input type="text" name="goal[content]" id= "goal
    _content" value="<%= @goal.content %>"></label>
    
  <label for="goal_ppublic" >
    <select name="goal[ppublic]" id="goal_ppublic">
      <option value="<%= true %>"<% "selected" if @goal.ppublic == true %>>Public</option>
      <option value="<%= false %>"<% "selected" unless @goal.ppublic ==true %>>Private</option>
    </select>
  </label>
      
  <label for="goal_completion" >
    <select name="goal[completion]" id="goal_completion">
    
      <option value="<%= true %>"<% "selected" if @goal.completion == true %>>Completed</option>
      <option value="<%= false %>"<% "selected" unless @goal.completion == true %>>Not Completed</option>
    </select>
  </label>

  <p><input type="submit" value="Update Goal"></p>
</form>

app/views/goals/new.html.erb
<h1>Create a Goal</h1>
<form action="<%= goals_url%>" method="post" accept-charset="utf-8">
  <label for="goal_content" >Content<input type="text" name="goal[content]" id= "goal
    _content" value="<%= @goal.content %>"></label><br>
    
  <label for="goal_ppublic" >Public
    <select name="goal[ppublic]" id="goal_ppublic">
      <option value="<%= true %>">Public</option>
      <option value="<%= false %>">Private</option>
    </select>
  </label><br>
      
  <label for="goal_completion" >Completed?
    <select name="goal[completion]" id="goal_completion">
    
      <option value="<%= true %>">Completed</option>
      <option value="<%= false %>">Not Completed</option>
    </select>
  </label><br>

  <p><input type="submit" value="Create a New Goal"></p>
</form>

app/views/goals/show.html.erb
<h2><%=@goal.content%></h2>
<p>Public: <%=@goal.ppublic%></p>
<p>Completion: <%=@goal.completion%></p>

<% if current_user == @goal.user%>
  <%=link_to "Edit Goal", edit_goal_url(@goal)%><br>
<% end %>
<%=link_to "Go back to my page", user_url(current_user)%>

app/views/layouts/_errors.html.erb
<%= flash[:errors].join('<br>').html_safe if flash[:errors]%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyGoalApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if logged_in? %>
<%= button_to('Log Out', session_url, method: :delete)%>
<%= current_user.user_name %>
<% else %>
<% link_to('Sign In', new_session_url)%>
<% link_to('Sign Up', new_user_url)%>
<% end %>

<%= render "layouts/errors"%>
<%= yield %>

</body>
</html>

app/views/users/index.html.erb
<h1>All Users</h1>

<ul>
  <%@users.each do |user|%>
    <li><%=link_to user.user_name, user_url(user)%></li>
  <%end%>
</ul>   

app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%=users_url%>" method="post" accept-charset="utf-8">
  <label for="username">
    Username
    <input type="text" id="username" name="user[user_name]" value="<%=@user.user_name%>">
  </label>
  
  <label for="password">
    Password
    <input type="password" id="password" name="user[password]" value="">
  </label>

  <p><input type="submit" value="Create User"></p>
</form>

app/views/users/show.html.erb
<h1>Goals</h1>
<ul>
  <% @user.goals.each do |goal| %>
    <%if goal.ppublic == true || @user == current_user%>
      <li><%= link_to goal.content, goal_url(goal)%></li>
    <%end%>
  <%end%>
</ul>


<%=link_to "All Users", users_url%><br>
<%=link_to "Create New Goal", new_goal_url%>